### ISSUE TITLE
[建议]行为一节的修订

### ISSUE THREAD

**Issue by odeinjul** [twitter-zh/twitter-zh.github.io#3]
**您知道如何正确填写吗**
请在下面打勾（即填入 `x` ）

- [x ] 我知道

**建议与意见**
行为/关注下
“关注 / 粉丝 大于 200：视奸号”
具有歧义，建议改为“关注 / 粉丝 大于 200：成熟的中推圈一员”

**Comment by twitter-zh** [comment]
已收到，稍候修改。

感谢您的建议！
